### ISSUE TITLE
Is the machine learning part of the project done on GPU or CPU?

### ISSUE THREAD

**Issue by hongyi-zhao** [colinbousige/BoroML#1]
I come across this project from [its corresponding paper](https://arxiv.org/pdf/2310.11245.pdf). But based on the code shown in this project, I still cannot figure out whether the machine learning part of the project is done on GPU or CPU, any hints will be helpful.

Regards,
Zhao

**Comment by colinbousige** [comment]
Hello Zhao,

The training is done on a cluster with CPUs, typically on a single node with 40 to 128 procs. The time it takes to reach convergence depends on the number of procs you use and the size of the dataset, but it is typically of the order of a few hours with a decent dataset size. To use n2p2 for the training, I refer you to their help page: https://compphysvienna.github.io/n2p2/topics/training.html

Note that the GitHub archive contains the weights resulting from the training, so you can directly use it in LAMMPS or python with ASE. We are currently working on a reactive version of this NNP, also with Au and Cu. We plan to submit a paper soon, and the resulting NNP will be uploaded here when it's done - hopefully in a few months.

Also, note that the arXiv paper is the preprint version before submission to JACS, the published one can be found on JACS: https://pubs.acs.org/doi/10.1021/jacs.3c11549

Best regards,
Colin

**Comment by hongyi-zhao** [comment]
> To use n2p2 for the training, I refer you to their help page: https://compphysvienna.github.io/n2p2/topics/training.html

Compared to [n2p2](https://github.com/CompPhysVienna/n2p2), [DeepMD-kit](https://github.com/deepmodeling/deepmd-kit) seems to have more powerful functions and also provides an interface with [LAMMPS](https://github.com/lammps/lammps), and it has consistently been under active development, whereas the most recent commit for [n2p2](https://github.com/CompPhysVienna/n2p2) was two years ago. Therefore, I don't understand why you wouldn't choose the latter for related research work.

**Comment by colinbousige** [comment]
Well, n2p2 also has an interface with LAMMPS, so there is no problem there.
For this project, we have used n2p2 because someone in our lab had already worked with it, so it was easier to get started with NNP development like that, and it worked fine for our needs. And this project started 1.5 years ago, when n2p2 was still active.
As for the choice of n2p2 versus DeepMD, it is true that DeepMD seems more active recently, so in the future we might switch to it.
